### ISSUE TITLE
一点建议

### ISSUE THREAD

**Issue by rdp-studio** [jiemo9527/pyexe#2]
自动切换代理不能翻墙？我要的不是这个。你可以参考[我们的一篇博客](https://blog.rdpstudio.top/deploy-proxypool-and-free-fq)搭建子代理池服务，然后从代理池抓，都是自动搜索的外国代理。

**Comment by jiemo9527** [comment]
> 自动切换代理不能翻墙？我要的不是这个。你可以参考[我们的一篇博客](https://blog.rdpstudio.top/deploy-proxypool-and-free-fq)搭建子代理池服务，然后从代理池抓，都是自动搜索的外国代理。

不是翻墙代理，国内爬虫用的代理。代理池太过辣鸡（80%不可用），我用的是付费的api或大平台白嫖（95%可用）。
你可能走理解错了，该工具只是用于快速切换访问者的ip，达到解除网站限制的需求

**Comment by jiemo9527** [comment]
> > 自动切换代理不能翻墙？我要的不是这个。你可以参考[我们的一篇博客](https://blog.rdpstudio.top/deploy-proxypool-and-free-fq)搭建子代理池服务，然后从代理池抓，都是自动搜索的外国代理。
> 
> 不是翻墙代理，国内爬虫用的代理。代理池太过辣鸡（80%不可用），我用的是付费的api或大平台白嫖（95%可用）。
> 你可能走理解错了，该工具只是用于快速切换访问者的ip，达到解除网站限制的需求。代理≠翻墙
